
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Health/ping command: a typed round trip UI -> shell -> core.
 */
async health() : Promise<Health> {
    return await TAURI_INVOKE("health");
},
/**
 * Open a web URL in the user's default browser. The webview does not follow `target="_blank"`
 * itself, so the UI hands outbound forge links here. Only http(s) is allowed.
 */
async openUrl(url: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_url", { url }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Sync every configured source now, independent of the scheduler's cadence. Emits a
 * `SyncProgressEvent` (with `done`/`total`) as each source completes, then returns the finished
 * list.
 */
async syncNow() : Promise<Result<SyncProgressEvent[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sync_now") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Every configured forge with its connection status (never its token).
 */
async listForges() : Promise<Result<ForgeView[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_forges") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Add a forge (kind `github` | `gitea`) with its API base URL and optional OAuth client id. The
 * user connects it afterwards, which stores the token in the keychain.
 */
async addForge(name: string, kind: string, baseUrl: string, oauthClientId: string | null) : Promise<Result<ForgeView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_forge", { name, kind, baseUrl, oauthClientId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Edit a forge's name, kind, base URL or OAuth client id. Credentials are managed separately.
 * Takes effect on the next app launch.
 */
async updateForge(id: string, name: string, kind: string, baseUrl: string, oauthClientId: string | null) : Promise<Result<ForgeView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_forge", { id, name, kind, baseUrl, oauthClientId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a forge and its stored credential. Fails if any board still points at it.
 */
async deleteForge(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_forge", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Connect a forge by storing a pasted personal access token in the keychain. Returns the forge
 * with `connected: true`.
 */
async setForgePat(forgeId: string, token: string) : Promise<Result<ForgeView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_forge_pat", { forgeId, token }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Disconnect a forge: remove its credential from the keychain. Returns the forge with
 * `connected: false`.
 */
async disconnectForge(forgeId: string) : Promise<Result<ForgeView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("disconnect_forge", { forgeId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Connect a GitHub forge via the OAuth device flow. Requests a device code, emits a
 * `DeviceAuthEvent` for the UI, then polls until the user authorizes or the code is denied or
 * expires. The token goes to the keychain, never to the DB or the UI. Only valid for a `github`
 * forge with a resolvable OAuth client id.
 */
async connectDeviceAuth(forgeId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("connect_device_auth", { forgeId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Whether a built-in GitHub OAuth client id exists, so the UI can offer "Connect with GitHub".
 */
async githubOauthAvailable() : Promise<boolean> {
    return await TAURI_INVOKE("github_oauth_available");
},
/**
 * What needs attention in a repo (`owner/name`): stale PRs, merged-without-review, failing CI,
 * over the synced store. Read-only; works with no token.
 */
async attention(fullName: string) : Promise<Result<AttentionView[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("attention", { fullName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * A repo's digest (`owner/name`): flow metrics, watchdog counts and a prose line. Read-only.
 */
async digest(fullName: string) : Promise<Result<DigestView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("digest", { fullName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The pull requests for a repo (`owner/name`), newest first, for the change picker. Read-only.
 */
async pullRequests(fullName: string) : Promise<Result<PullRequestView[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pull_requests", { fullName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The change digest for one pull request (by id). `null` if there is no such PR. Read-only.
 */
async changeDigest(prId: string) : Promise<Result<ChangeDigestView | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_digest", { prId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Every registered tracker (Jira site). Read-only.
 */
async listTrackers() : Promise<Result<TrackerView[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_trackers") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Register a Jira site (URL + optional Cloud email). The API token is set separately in the
 * keychain; a public instance needs none.
 */
async addTracker(name: string, baseUrl: string, email: string | null) : Promise<Result<TrackerView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_tracker", { name, baseUrl, email }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Store a Jira API token in the keychain for a tracker. An empty token clears it.
 */
async setTrackerToken(trackerId: string, token: string) : Promise<Result<TrackerView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_tracker_token", { trackerId, token }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a tracker, its board links and its stored token.
 */
async deleteTracker(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_tracker", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Link a Jira project (by key) to a board. Returns the board's links.
 */
async linkBoardTracker(boardId: string, trackerId: string, projectKey: string) : Promise<Result<BoardTrackerView[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("link_board_tracker", { boardId, trackerId, projectKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Unlink a Jira project from a board. Returns the remaining links.
 */
async unlinkBoardTracker(boardId: string, trackerId: string, projectKey: string) : Promise<Result<BoardTrackerView[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unlink_board_tracker", { boardId, trackerId, projectKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The board's Jira tickets, sprints and project links. Read-only.
 */
async boardJira(id: string) : Promise<Result<BoardJiraView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("board_jira", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Semantic search over indexed activity text: hybrid retrieval (vector + keyword) then reranking,
 * excluding code chunks, within the board's repos. Read-only; works with no token.
 */
async semanticSearch(boardId: string, query: string, k: number) : Promise<Result<SearchHit[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("semantic_search", { boardId, query, k }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Semantic search over indexed source code: hybrid retrieval then reranking, restricted to `code`
 * chunks (file path + snippet) in the board's repos. The code index is filled by
 * `SyncEngine::sync_code`. Read-only; works with no token.
 */
async semanticCodeSearch(boardId: string, query: string, k: number) : Promise<Result<SearchHit[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("semantic_code_search", { boardId, query, k }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Report backend status and current store/index counts. Read-only; works with no token. The
 * embedder/reranker names are what is loaded, not what was requested.
 */
async debugStats() : Promise<Result<DebugStatsView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("debug_stats") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The live index lane alone: the rows of `debug_stats.index_active` without the store-wide
 * counts. The board shell polls this to keep each repo's index badge current.
 */
async indexStatus() : Promise<Result<IndexEntryView[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("index_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Every repo in the store, marked with whether a board pins or discovers it. Read-only.
 * Repos nothing watches come first.
 */
async storedRepos() : Promise<Result<StoredRepoView[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stored_repos") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Measure what is on disk: the database, broken down, and the model assets beside it. Read-only.
 * Kept out of `debug_stats`: `dbstat` walks every page and the per-repo sums scan the payload
 * tables, while the Debug view re-runs `debug_stats` on every sync event.
 */
async storageReport() : Promise<Result<StorageReportView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("storage_report") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The live storage state. Read-only.
 */
async storageState() : Promise<Result<StorageStateView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("storage_state") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Drop one repo's search index. Activity and metric snapshots stay; the next sync rebuilds it.
 */
async dropRepoIndex(repoId: string) : Promise<Result<DroppedIndexView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("drop_repo_index", { repoId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Give the free pages back to the file system: `VACUUM`, then truncate the log. Deletes nothing.
 * A delete does not shrink a SQLite file, so this is the only way under the ceiling after one.
 * Slow and exclusive: it needs room for a second copy while it holds the write lock.
 */
async reclaimFreeSpace() : Promise<Result<ReclaimReportView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reclaim_free_space") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Remove a repo and everything derived from it. Destructive and irreversible; the UI confirms
 * first. Refuses while a board pins the repo or a source still schedules it, and the error names
 * what holds it. A repo a board's person still owns is discovered again on the next pass.
 */
async forgetRepo(repoId: string) : Promise<Result<ForgottenRepoView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("forget_repo", { repoId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The orphan repo report: repos left behind by a deleted board's pin or discovery, which nothing
 * else cleans up. Read-only.
 */
async orphanRepos() : Promise<Result<OrphanRepoReportView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("orphan_repos") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Remove every repo no board references, and everything derived from each: `forget_repo`'s
 * removal for the whole orphan set in one transaction. Destructive and irreversible. Never
 * refuses: each repo is already unpinned and undiscovered by construction.
 */
async reclaimOrphanRepos() : Promise<Result<OrphanReclaimView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reclaim_orphan_repos") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create a board of the given kind ("team" | "repo" | "org") on the given forge. The forge is
 * required and fixed for the board's life. For a repo/org board, `target` is its one repo
 * (`owner/name`) or org login: it is set immediately, names the board (`name` is ignored) and
 * cannot change later. A team board takes `name` and starts with empty, editable scope.
 * Idempotent by the name's slug id. Returns the board.
 */
async createBoard(name: string, kind: string, forgeId: string, target: string | null) : Promise<Result<BoardView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_board", { name, kind, forgeId, target }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Every board, each with its people and pinned repos.
 */
async listBoards() : Promise<Result<BoardView[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_boards") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a board (its members go with it).
 */
async deleteBoard(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_board", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Add a person (GitHub login) to a board. Returns the updated board.
 */
async addBoardPerson(id: string, login: string) : Promise<Result<BoardView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_board_person", { id, login }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Remove a person from a board. Returns the updated board.
 */
async removeBoardPerson(id: string, login: string) : Promise<Result<BoardView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_board_person", { id, login }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Pin a repo (`owner/name`) to a board and register it as a synced source. Returns the board.
 */
async addBoardRepo(id: string, fullName: string) : Promise<Result<BoardView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_board_repo", { id, fullName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Search a forge for users matching `query`, for the source pickers. Forge-scoped so it works
 * before any board exists. Read-only.
 */
async searchForgeUsers(forgeId: string, query: string) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_forge_users", { forgeId, query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Search a forge for orgs matching `query`. See [`search_forge_users`].
 */
async searchForgeOrgs(forgeId: string, query: string) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_forge_orgs", { forgeId, query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Search a forge for repos (`owner/name`) matching `query`. See [`search_forge_users`].
 */
async searchForgeRepos(forgeId: string, query: string) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_forge_repos", { forgeId, query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Unpin a repo from a board. If no other board pins it, it stops being a synced source.
 * Returns the updated board.
 */
async removeBoardRepo(id: string, fullName: string) : Promise<Result<BoardView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_board_repo", { id, fullName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set or clear a board's org restriction (an empty string clears it). When set, only repos in
 * that org are discovered from the board's people. Returns the updated board.
 */
async setBoardOrg(id: string, org: string | null) : Promise<Result<BoardView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_board_org", { id, org }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Toggle whether a team board's people-derived discovery includes archived repositories.
 * Explicitly pinned repositories are always in scope. Returns the updated board.
 */
async setBoardIncludeArchived(id: string, includeArchived: boolean) : Promise<Result<BoardView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_board_include_archived", { id, includeArchived }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Toggle whether a repo's source code is indexed for code search. Off skips the code fetch and
 * embed and drops the repo's existing code index. Returns the new value.
 */
async setRepoIndexCode(repoId: string, enabled: boolean) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_repo_index_code", { repoId, enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * A board's attention-signal preferences: every toggleable signal and whether this board flags
 * it. Read-only; works with no token.
 */
async boardSignals(id: string) : Promise<Result<SignalPrefView[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("board_signals", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Enable or disable one attention signal for a board. Returns the updated preference list.
 */
async setBoardSignalEnabled(id: string, signal: string, enabled: boolean) : Promise<Result<SignalPrefView[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_board_signal_enabled", { id, signal, enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * A per-repo overview line for a board: the repo plus its digest and attention count. Total
 * attention payload is bounded to `MAX_BOARD_ATTENTION_ITEMS`; each repo keeps its true
 * `attention_total` so the UI can say "showing N of M".
 */
async boardOverview(id: string) : Promise<Result<RepoOverview[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("board_overview", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * DORA-lite metrics for a board, pooled across its repos.
 */
async boardDora(id: string) : Promise<Result<DoraView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("board_dora", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Attention rolled up across a board: the union of its repos' items, with the board's people
 * flagged. Read-only; works with no token.
 */
async boardAttention(id: string) : Promise<Result<BoardAttentionView[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("board_attention", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Every pull request across a board's effective repos, for the Changes grid. Sorted and filtered
 * client-side; a row's digest loads on click via `change_digest`. Read-only.
 */
async boardChanges(id: string) : Promise<Result<BoardPrView[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("board_changes", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The standup agenda for a whole board over a window: what moved within `since_days..until_days`
 * ago (day offsets from now; `until_days` 0 means now, so "this week" is 7..0 and "last week"
 * is 14..7), what waits on review, and what needs attention. Read-only; works with no token.
 */
async boardStandup(id: string, sinceDays: number, untilDays: number) : Promise<Result<BoardStandupView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("board_standup", { id, sinceDays, untilDays }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * One person's activity across a board's effective repos: open PRs and merged-PR, review and
 * commit counts. Read-only over the synced store; works with no token.
 */
async personActivity(id: string, login: string) : Promise<Result<PersonActivityView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("person_activity", { id, login }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Comparison stats for every person on a board over a window: per-person throughput and current
 * load, plus one team-level off-hours counter (never per person). Read-only; works with no token.
 */
async boardPeopleStats(id: string, sinceDays: number, untilDays: number) : Promise<Result<BoardPeopleStatsView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("board_people_stats", { id, sinceDays, untilDays }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The board's "who can pick this up" panel: per person, in-flight load, last-active time and
 * areas of context. Descriptive, not a ranking. The roster is the board's people, or
 * contributors discovered from activity, in a stable order. Read-only; works with no token.
 */
async boardPickup(id: string, sinceDays: number, untilDays: number) : Promise<Result<PersonPickupView[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("board_pickup", { id, sinceDays, untilDays }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The board's investment distribution over a window: merged PRs classified into feature / bug /
 * maintenance / docs / test / other by conventional-commit title and linked bug work items, by
 * count and churn. Read-only; works with no token.
 */
async boardInvestment(id: string, sinceDays: number, untilDays: number) : Promise<Result<InvestmentDistributionView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("board_investment", { id, sinceDays, untilDays }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * A board's epic/initiative progress: Jira issues rolled up to their parent epics, with a
 * stalled-work at-risk flag. Empty when the board has no Jira parents. Read-only; no token.
 */
async boardEpics(id: string) : Promise<Result<EpicProgressView[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("board_epics", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stream the board's AI brief: rephrase the deterministic attention brief with the local model,
 * emitting `BriefEvent`s (thinking -> delta* -> done). When the `llm` feature is off or no model
 * is configured, emits a single `disabled`. Local-first; no key, no network. Returns once
 * generation ends.
 */
async startBoardBrief(id: string, runId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_board_brief", { id, runId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Answer a question with the conversational assistant: a Rig agent over the local model that
 * calls read-only KB tools scoped to `board_id` and grounds its reply via RAG. Streams
 * `AssistantChatEvent` (thinking -> delta -> done), or a single `disabled` when the assistant is
 * not built in or no model is ready. Local-first; no key, no network.
 */
async startAssistantChat(runId: string, boardId: string, history: ChatTurnView[], question: string, tab: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_assistant_chat", { runId, boardId, history, question, tab }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The local-LLM settings and model catalog. Read-only; no token.
 */
async llmCatalog() : Promise<Result<LlmCatalogView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("llm_catalog") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set the local-LLM runtime switch and selected model. Returns the updated settings.
 */
async setLlmSettings(enabled: boolean, model: string | null) : Promise<Result<SettingsView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_llm_settings", { enabled, model }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Download a GGUF model from Hugging Face into the writable models dir, streamed to disk and
 * emitting `LlmDownloadEvent` progress. Writes a `.part` file, then renames on success. Egress
 * happens only when the user clicks Download.
 */
async downloadLlmModel(repo: string, file: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_llm_model", { repo, file }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The Portfolio overview: every board with its daily trend series. Boards are in stored order;
 * a descriptive overview, not a ranking. Read-only; works with no token.
 */
async portfolio() : Promise<Result<PortfolioBoardView[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("portfolio") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async personWorkPattern(id: string, login: string, sinceDays: number, untilDays: number) : Promise<Result<WorkPatternView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("person_work_pattern", { id, login, sinceDays, untilDays }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * A board's metric trend: per day, totals across the board's effective repos. Read-only over
 * recorded snapshots; works with no token. Empty until snapshots accumulate.
 */
async boardTrend(id: string) : Promise<Result<TrendPointView[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("board_trend", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * A board's week-over-week deltas and anomaly flags over its daily snapshots.
 */
async boardTrendSummary(id: string) : Promise<Result<TrendDeltasView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("board_trend_summary", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The hottest files across a board's repos: change frequency x churn, generated/vendored paths
 * excluded. The Code tab renders these as a treemap.
 */
async boardHotspots(id: string) : Promise<Result<HotspotView[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("board_hotspots", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The riskiest files across a board's repos: hotspot x ownership x review per file, with
 * drill-to-PR. The Code tab renders these as an explainable risk list.
 */
async boardCodeRisk(id: string) : Promise<Result<CodeRiskView[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("board_code_risk", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The weakest files across a board's repos by AST health score, lowest first, capped at 40. Only
 * parsed files are scored, so a file in a language with no tree-sitter grammar is absent, not
 * healthy. Empty when code indexing has not run.
 */
async boardCodeHealth(id: string) : Promise<Result<FileHealthView[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("board_code_health", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * At-risk modules across a board's repos: low bus factor or high concentration ("module X has
 * bus factor N, top owner <login> at S%"). Framed as code risk, never a ranking of people.
 */
async boardOwnershipRisks(id: string) : Promise<Result<OwnershipRiskView[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("board_ownership_risks", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Top change-coupling pairs across a board's repos. Shown on the Code tab beside hotspots.
 */
async boardCoupling(id: string) : Promise<Result<CouplingPairView[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("board_coupling", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The dependencies across a board's repos, each with the repos that use it; dependencies shared
 * by more than one repo lead. The Code tab renders a list and graph.
 */
async boardDependencies(id: string) : Promise<Result<DepUsageView[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("board_dependencies", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * A board's scorecards: per-repo Bronze/Silver/Gold plus a composite (the weakest repo's tier).
 * Composes flow, CI and ownership signals; rules-before-LLM, no people ranking.
 */
async boardScorecard(id: string) : Promise<Result<BoardScorecardView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("board_scorecard", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async boardLinkCoverage(id: string) : Promise<Result<LinkCoverageView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("board_link_coverage", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async boardFlowMetrics(id: string, sinceDays: number, untilDays: number) : Promise<Result<FlowMetricsView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("board_flow_metrics", { id, sinceDays, untilDays }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async boardCyclePhases(id: string) : Promise<Result<BoardCyclePhasesView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("board_cycle_phases", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async boardBugFlow(id: string, sinceDays: number, untilDays: number) : Promise<Result<BugFlowView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("board_bug_flow", { id, sinceDays, untilDays }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Say-do for every Jira sprint a board watches, newest first. Only sprints with a frozen
 * commitment.
 */
async boardSayDo(id: string) : Promise<Result<SayDoView[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("board_say_do", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * A board's say-do velocity trend, oldest sprint first. The order comes from core
 * (`velocity_trend`, by commitment date); the UI plots it as given. `filter_map` only unwraps
 * fields core guarantees, so the view has no nullable ratio.
 */
async boardVelocityTrend(id: string) : Promise<Result<VelocityPointView[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("board_velocity_trend", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async boardFlowTrend(id: string) : Promise<Result<FlowTrendView[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("board_flow_trend", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async boardDigest(id: string, sinceDays: number, untilDays: number) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("board_digest", { id, sinceDays, untilDays }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Push a board's standup digest to the configured webhook on demand. Egress only on this call
 * with a configured URL.
 */
async sendBoardDigest(id: string, sinceDays: number, untilDays: number) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_board_digest", { id, sinceDays, untilDays }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Toggle opt-in dependency vulnerability scanning for a board. Returns the updated board.
 */
async setBoardScanDependencies(id: string, enabled: boolean) : Promise<Result<BoardView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_board_scan_dependencies", { id, enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Scan a board's dependency packages against the OSV advisory database. Network egress; only
 * runs when the board has scanning enabled. Package-level (version-imprecise).
 */
async scanBoardDependencies(id: string) : Promise<Result<PackageAdvisoryView[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("scan_board_dependencies", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The current application settings. Read-only; no token.
 */
async getSettings() : Promise<Result<SettingsView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Update the application settings. `sync_period_secs` is the scheduler poll cadence (>= 1s,
 * applied on the next pass); `stale_pr_days` is the open-PR staleness threshold (>= 1).
 * Returns the new values.
 */
async setSettings(syncPeriodSecs: number, stalePrDays: number, digestWebhookUrl: string | null, digestScheduleHours: number | null, storageBudgetMb: number | null) : Promise<Result<SettingsView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_settings", { syncPeriodSecs, stalePrDays, digestWebhookUrl, digestScheduleHours, storageBudgetMb }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
assistantChatEvent: AssistantChatEvent,
briefEvent: BriefEvent,
deviceAuthEvent: DeviceAuthEvent,
indexProgressEvent: IndexProgressEvent,
llmDownloadEvent: LlmDownloadEvent,
syncProgressEvent: SyncProgressEvent
}>({
assistantChatEvent: "assistant-chat-event",
briefEvent: "brief-event",
deviceAuthEvent: "device-auth-event",
indexProgressEvent: "index-progress-event",
llmDownloadEvent: "llm-download-event",
syncProgressEvent: "sync-progress-event"
})

/** user-defined constants **/



/** user-defined types **/

/**
 * One on-disk asset outside the database: a model directory, or the app data dir itself.
 */
export type AssetStorageView = { name: string;
/**
 * "llm_downloaded" | "llm_bundled" | "embed_model" | "rerank_model" | "app_data".
 */
kind: string; path: string; exists: boolean; bytes: number; files: number;
/**
 * True for an entry that contains other entries (the app data dir), so a UI does not add it
 * into a total alongside them.
 */
includes_others: boolean }
/**
 * One streamed step of an assistant chat turn, tagged with the `run_id` of the
 * `start_assistant_chat` call so overlapping turns do not interleave. `phase` is "thinking"
 * (running tools or generating), "delta" (a piece of the answer in `delta`), "done", "disabled"
 * (feature off or no model), or "error" (the agent failed mid-turn; `delta` carries the message).
 */
export type AssistantChatEvent = { run_id: string; phase: string; delta: string }
/**
 * One concrete thing an attention item points at, with everything a surface needs to name and
 * link it. `url` is whatever web URL the forge reported; `None` renders as plain text. Nothing
 * is composed from a URL convention.
 */
export type AttentionEntity = { type: "pull_request"; id: string; number: number; title: string; url: string | null } |
/**
 * A tracked work item (a forge issue, or a Jira issue).
 */
{ type: "work_item"; id: string; number: number; title: string; url: string | null } | { type: "ci_run"; id: string; commit_sha: string | null; attempt: number | null; url: string | null } |
/**
 * A person, by forge login. No URL: a profile URL is not synced, and the surface that shows a
 * login already composes one from the board's forge web root.
 */
{ type: "person"; login: string } |
/**
 * A file in the repo the item belongs to.
 */
{ type: "source_file"; path: string; last_changed_at: string | null }
/**
 * Why an entity is attached to an attention item: the flagged thing, the person to nudge, or
 * the fact that makes the flag true.
 */
export type AttentionRole =
/**
 * The thing the signal is about. Exactly one per item.
 */
"subject" |
/**
 * Who the next step points at (the PR's author). Omitted if unknown.
 */
"actor" |
/**
 * The fact that makes the flag true, e.g. the open work item behind `done_not_done`.
 */
"evidence"
/**
 * One attention item for the UI. Boundary form of `core_summary::AttentionItem`.
 */
export type AttentionView = { kind: string;
/**
 * The typed envelope: the flagged `subject`, who to nudge as `actor`, and the `evidence`. Its
 * identity and outbound links; passed through from `core_model`.
 */
entities: LinkedEntity[]; summary: string;
/**
 * Which repo this item is on. Filled by the caller; `None` if not set.
 */
repo_full_name: string | null;
/**
 * When the flagged thing happened, so the Attention tab can scope to a recent window.
 */
ts: string | null;
/**
 * The deterministic mechanical next step. Empty when there is none.
 */
action: string;
/**
 * For `aging_wip` items: band of the board's in-progress-time distribution.
 * "over_p50" | "over_p75" | "over_p90", or null with too little history.
 */
wip_percentile: string | null;
/**
 * What `wip_percentile` is measured over: span, window and sample size. Shown on the badge.
 */
wip_percentile_basis: string | null }
/**
 * A board-level attention item. Boundary form of `core_summary::BoardAttentionItem`.
 */
export type BoardAttentionView = { repo_id: string; kind: string;
/**
 * The item's typed envelope, the same shape as the per-repo `AttentionView`.
 */
entities: LinkedEntity[]; summary: string; by_team: boolean;
/**
 * For `aging_wip` items: band of the board's in-progress-time distribution.
 */
wip_percentile: string | null;
/**
 * What `wip_percentile` is measured over: span, window and sample size.
 */
wip_percentile_basis: string | null }
/**
 * A board's PR delivery-cycle phase medians: pickup (open -> first review), review (-> merge).
 */
export type BoardCyclePhasesView = { median_pickup_secs: number | null; median_review_secs: number | null }
/**
 * A board's Jira surface: its watched projects' tickets and sprints.
 */
export type BoardJiraView = { tickets: JiraTicketView[]; sprints: JiraSprintView[];
/**
 * The board's linked projects (empty = no Jira on this board).
 */
projects: BoardTrackerView[] }
/**
 * The board People comparison: per-person throughput rows plus one team-level off-hours
 * sustainability counter, never attributed to an individual. Boundary form of
 * `core_summary::BoardPeopleStats`.
 */
export type BoardPeopleStatsView = { people: PersonStatsView[]; off_hours_events: number; total_events: number }
/**
 * A board-wide pull request row for the Changes grid: boundary form of `core_summary::BoardPr`
 * plus the repo's `full_name`.
 */
export type BoardPrView = { repo_id: string; full_name: string; id: string; number: number; title: string; state: string; author_login: string | null; created_at: string; merged_at: string | null; review_count: number; approved: boolean; url: string | null }
/**
 * A board's scorecard composite for the UI.
 */
export type BoardScorecardView = { composite_tier: string; gold: number; silver: number; bronze: number; none: number; repos: ScorecardView[] }
/**
 * A board's standup agenda, rolled up across the board's repos.
 */
export type BoardStandupView = { board_id: string; since: string; until: string; moved_commits: number; merged_prs: PrRefView[]; waiting_on_review: PrRefView[];
/**
 * Issues delivered (closed) in the window, and open issues in progress.
 */
delivered_issues: IssueRefView[]; in_progress_issues: IssueRefView[]; needs_attention: AttentionView[] }
/**
 * A board's link to a tracker project, with the tracker's display name.
 */
export type BoardTrackerView = { tracker_id: string; tracker_name: string; project_key: string }
/**
 * A board for the UI. Boundary form of `core_store::Board`.
 */
export type BoardView = { id: string; name: string;
/**
 * What the board watches: "team" | "repo" | "org". Drives scope inputs, visible tabs and
 * indexing profile. Fixed at creation.
 */
kind: string;
/**
 * GitHub logins on the board (the people watched).
 */
people: string[];
/**
 * `owner/name` of each pinned repo. Empty = the board covers everything its people touch.
 */
repos: string[];
/**
 * Optional org restriction: only repos in this org are discovered. `None` = no limit.
 */
org: string | null;
/**
 * The forge this board syncs from. `None` = unassigned; the board cannot be synced.
 */
forge_id: string | null;
/**
 * Opt-in dependency vulnerability scanning. Off by default.
 */
scan_dependencies: boolean;
/**
 * Whether a team board's people-derived discovery includes archived repositories. Off by
 * default; direct repository pins bypass this.
 */
include_archived: boolean }
/**
 * One streamed step of the AI brief, tagged with the board and the `run_id` of the
 * `start_board_brief` call, so the UI accepts only its own stream: one board can have two
 * overlapping generations in flight (StrictMode double mount) and their tokens would interleave.
 * `phase` is "loading"/"prefilling"/"thinking" (before the first token), "delta" (a token in
 * `delta`), "done", or "disabled" (no model or `llm` feature off).
 */
export type BriefEvent = { run_id: string; board_id: string; phase: string; delta: string }
/**
 * A board's bug inflow vs outflow over a window: bug-labeled issues opened vs closed.
 */
export type BugFlowView = { opened: number; closed: number }
/**
 * A per-change digest. Boundary form of `core_summary::ChangeDigest`. `body` is the PR's
 * Markdown description, rendered in the UI; `files` is the diff.
 */
export type ChangeDigestView = { pr_id: string; number: number; title: string; state: string; author_login: string | null; body: string | null; review_count: number; approved: boolean; linked_issues: LinkedIssueView[];
/**
 * Jira tickets linked to this PR via a `PROJ-123` key. Filled by the command.
 */
linked_tickets: JiraTicketView[]; files: ChangedFileView[]; additions: number; deletions: number; prose: string }
/**
 * A file a change touched. Boundary form of `core_summary::ChangedFile`.
 */
export type ChangedFileView = { filename: string; status: string; additions: number; deletions: number; patch: string | null }
/**
 * One prior turn of the conversation, sent from the UI for context. `role` is "user" or
 * "assistant".
 */
export type ChatTurnView = { role: string; content: string }
/**
 * A PR that touched a code-risk file, for the drill-down.
 */
export type CodeRiskPrView = { number: number; title: string; url: string | null }
/**
 * A file's code risk: hotspot x ownership x review, with the components, plain-language reasons
 * and the recent PRs that touched it. Code risk, not a people ranking.
 */
export type CodeRiskView = { repo_id: string; full_name: string; path: string; changes: number; churn: number; authors: number; top_author: string; top_share: number; bus_factor: number; merged_touches: number; unreviewed: number; review_gap: number; score: number; reasons: string[]; recent_prs: CodeRiskPrView[] }
/**
 * A change-coupling pair: two files in the same repo that often change in the same merged PR.
 * Implicit coupling not visible in the dependency graph.
 */
export type CouplingPairView = { repo_id: string; full_name: string; path_a: string; path_b: string;
/**
 * Merged PRs where both files changed together.
 */
together: number;
/**
 * Jaccard coupling strength: `together / (prs_a + prs_b - together)`.
 */
coupling: number }
/**
 * Backend and store/index status for the Debug view: the active embedder/reranker plus
 * `core_store::StoreCounts`.
 */
export type DebugStatsView = {
/**
 * The active embedder's name (real model or deterministic fallback) and its dimension.
 */
embedder: string; embedder_dims: number;
/**
 * The active reranker's name ("none" for the no-op).
 */
reranker: string;
/**
 * Whether the `fastembed` feature is built into this binary.
 */
fastembed_built: boolean; db_path: string;
/**
 * Jobs waiting in the background index queue; 0 if empty or no engine/queue.
 */
index_queue_depth: number; repos: number; commits: number; pull_requests: number; issues: number; sources: number; boards: number; embeddings_total: number; embeddings_code: number; embeddings_activity: number; code_files: number;
/**
 * Repos currently in the index lane (queued / indexing / errored), for the Debug panel.
 */
index_active: IndexEntryView[];
/**
 * Local-LLM narrator status, including why the AI brief falls back when it does.
 */
llm: LlmStatusView }
/**
 * A dependency used across a board: the repos (by full name) that declare it.
 */
export type DepUsageView = { ecosystem: string; name: string; repos: string[] }
/**
 * A started device-flow authorization, pushed to the UI to show `user_code` and open
 * `verification_uri`.
 */
export type DeviceAuthEvent = { forge_id: string; user_code: string; verification_uri: string }
/**
 * A repo's at-a-glance digest. Boundary form of `core_summary::Digest`.
 */
export type DigestView = { generated_at: string; median_cycle_time_secs: number | null;
/**
 * Cycle-time phase medians: pickup = created -> first review, review = first review -> merge.
 */
median_pickup_secs: number | null; median_review_secs: number | null; wip: number; stale_open_prs: number; merged_without_review: number;
/**
 * Open, unmerged PRs waiting for a first review past the review-wait threshold.
 */
review_wait: number; review_concentration: number; prose: string }
/**
 * DORA-lite metrics. Boundary form of `core_summary::DoraMetrics`. Deploy frequency is measured;
 * lead time and change failure rate are proxies (the UI marks them).
 */
export type DoraView = { window_days: number; deploy_frequency_per_week: number | null; deploy_tier: string; lead_time_secs: number | null; lead_tier: string;
/**
 * True when lead time is the deploy-based value, false when it is the cycle-time proxy.
 */
lead_from_deploys: boolean; change_failure_rate: number | null; cfr_tier: string }
/**
 * What dropping one repo's search index removed. Every figure is rebuilt by the next sync.
 */
export type DroppedIndexView = { repo_id: string; found: boolean; chunks: number; code_files: number; total_rows: number }
/**
 * One epic/initiative's progress: children done / total / in-progress plus an at-risk flag.
 * Child-count based, board-level.
 */
export type EpicProgressView = { key: string; title: string; total: number; done: number; in_progress: number; at_risk: boolean }
/**
 * A file's AST health score for the UI Code tab.
 */
export type FileHealthView = { repo_id: string; full_name: string; path: string; loc: number; functions: number; branches: number;
/**
 * Health score 1-10 (10 = simplest), from branch density and LOC.
 */
score: number }
/**
 * A board's work-item flow: lead time and WIP from the derived status history. Empty on a board
 * with no linked GitHub issues. Read-only; works with no token.
 */
export type FlowMetricsView = { completed: number; median_lead_time_secs: number | null; median_wait_secs: number | null; median_active_secs: number | null; in_progress: number; median_in_progress_age_secs: number | null }
/**
 * One day of a board's flow/quality trend. Boundary form of `core_summary::FlowTrendPoint`.
 */
export type FlowTrendView = { captured_on: string; lead_time_secs: number | null; wip: number; bug_net: number }
/**
 * A configured forge: non-secret config plus `connected`. The token never crosses the boundary.
 */
export type ForgeView = { id: string; name: string;
/**
 * "github" | "gitea".
 */
kind: string; base_url: string;
/**
 * The GitHub OAuth app client id for the device flow (public). `None` = PAT-only.
 */
oauth_client_id: string | null;
/**
 * Whether a credential is stored for this forge in the OS keychain.
 */
connected: boolean }
/**
 * What forgetting a repo removed. Boundary form of `core_store::ForgottenRepo`.
 */
export type ForgottenRepoView = { repo_id: string; found: boolean; commits: number; pull_requests: number; issues: number; code_files: number; index_chunks: number; total_rows: number }
/**
 * Result of the health/ping command. Proves a typed round trip from the UI into core.
 */
export type Health = {
/**
 * Always "ok" while the core is responsive.
 */
status: string;
/**
 * The core crate version, so the UI can show what it is talking to.
 */
core_version: string }
/**
 * A code hotspot: a file that changes often and churns a lot.
 */
export type HotspotView = { repo_id: string; full_name: string; path: string; changes: number; churn: number; authors: number; score: number }
/**
 * One repo's index-lane state, for the Debug "Queues" panel. `done`/`total` carry the embedding
 * sub-progress while `indexing` (0 otherwise).
 */
export type IndexEntryView = { repo_id: string; full_name: string; state: string; done: number; total: number;
/**
 * The failure reason when `state` is "error" (else null).
 */
error: string | null;
/**
 * Files still to index when `state` is "partial"; 0 otherwise.
 */
pending: number;
/**
 * Files this pass could not fetch when `state` is "partial"; 0 otherwise.
 */
skipped: number;
/**
 * Why a "partial" or "paused" state holds. Separate from `error`: neither is a failure.
 */
note: string | null }
/**
 * A per-repo background-indexing update. Boundary form of `core_sync::IndexProgress`. `state`
 * is "indexing" | "indexed" | "error" (the host also derives "queued" from a fetch-completed
 * event). Drives the per-repo index badge.
 */
export type IndexProgressEvent = { repo_id: string; full_name: string; state: string; files: number;
/**
 * Embedding sub-progress while `indexing` (units done / total this pass); 0 otherwise.
 * Shown as a percentage on the index badge.
 */
done: number; total: number;
/**
 * The failure reason when `state` is "error" (else null).
 */
error: string | null;
/**
 * Files still to index when `state` is "partial"; 0 otherwise.
 */
pending: number;
/**
 * Files this pass could not fetch when `state` is "partial"; 0 otherwise.
 */
skipped: number;
/**
 * Why a "partial" or "paused" state holds. Separate from `error`: neither is a failure, and a
 * red badge would send the user hunting for one.
 */
note: string | null }
/**
 * One investment category's share: merged-PR count (primary) and churn (secondary).
 */
export type InvestmentBucketView = { category: string; count: number; churn: number }
/**
 * Where a board's delivered effort went over a window: merged PRs grouped into investment
 * categories. Board-level, not per person.
 */
export type InvestmentDistributionView = { buckets: InvestmentBucketView[]; total_count: number; total_churn: number }
/**
 * A tracked issue on the standup. Boundary form of `core_ritual::IssueRef`.
 */
export type IssueRefView = { id: string; number: number; title: string }
/**
 * A Jira sprint for the UI.
 */
export type JiraSprintView = { name: string; state: string | null; starts_on: string | null; ends_on: string | null }
/**
 * A Jira ticket. Boundary form of `core_store::JiraIssueRow`.
 */
export type JiraTicketView = { key: string; title: string; issue_type: string; status: string; status_category: string | null; assignee: string | null; url: string | null; updated_at: string | null; resolved_at: string | null }
/**
 * A board's work-item link coverage: the share of merged PRs that resolve to a work-item link,
 * with the authoritative `closes` count split out.
 */
export type LinkCoverageView = { merged_total: number; linked: number; closes: number }
/**
 * An entity attached to an attention item, with the reason it is attached.
 */
export type LinkedEntity = { role: AttentionRole; target: AttentionEntity }
/**
 * A linked issue on a change digest. Boundary form of `core_summary::LinkedIssue`.
 */
export type LinkedIssueView = { id: string; number: number; title: string; relation: string }
/**
 * The local-LLM settings and catalog for the Settings tab.
 */
export type LlmCatalogView = {
/**
 * Whether the `llm` feature is compiled into this binary.
 */
feature_built: boolean;
/**
 * The runtime on/off switch.
 */
enabled: boolean;
/**
 * The selected GGUF filename, or null (env default).
 */
selected: string | null;
/**
 * Where models are stored and downloaded to.
 */
dir: string; models: LlmModelView[] }
/**
 * Progress of a local-LLM model download. `done`/`error` terminate it.
 */
export type LlmDownloadEvent = { file: string; received: number; total: number; done: boolean; error: string | null }
/**
 * One model in the curated local-LLM catalog: a small instruct GGUF that runs on CPU.
 */
export type LlmModelView = { label: string; repo: string; file: string; params: string; size: string;
/**
 * Whether the GGUF is present in the models dir.
 */
downloaded: boolean }
/**
 * The local-LLM narrator's runtime status for the Debug panel.
 */
export type LlmStatusView = {
/**
 * Whether the `llm` feature is compiled into this binary.
 */
feature_built: boolean;
/**
 * Whether a model is configured (both env vars set).
 */
configured: boolean;
/**
 * The configured `dir/file`, if any.
 */
model_path: string | null;
/**
 * Whether that GGUF file exists on disk.
 */
model_present: boolean;
/**
 * Whether the model has been loaded this session (the first brief loads it).
 */
loaded: boolean;
/**
 * The most recent engine error (model load / generation), or null if the last run was clean.
 */
last_error: string | null }
/**
 * One metric's week-over-week movement for the UI.
 */
export type MetricDeltaView = { metric: string; current: number; previous: number; delta: number; anomaly: boolean;
/**
 * True when the anomaly was decided against the same-weekday baseline, so the UI can say
 * "unusual for a <weekday>".
 */
seasonal: boolean }
/**
 * What reclaiming every orphaned repo removed, the bulk form of `ForgottenRepoView`.
 */
export type OrphanReclaimView = { repo_ids: string[]; count: number; total_rows: number }
/**
 * What no board can reach at all, pinned or discovered, before the user decides to reclaim it.
 */
export type OrphanRepoReportView = { repos: OrphanRepoView[]; count: number; rows: number; estimated_bytes: number }
/**
 * One orphaned repo, sized as the Debug storage card sizes any repo.
 */
export type OrphanRepoView = { repo_id: string; full_name: string; rows: number; estimated_bytes: number }
/**
 * A module's ownership risk for the UI. Code risk, not a people ranking.
 */
export type OwnershipRiskView = { repo_id: string; full_name: string; module: string; changes: number; authors: number; top_author: string; top_share: number; bus_factor: number }
/**
 * A dependency package with known advisories. Package-level: manifests declare ranges, not
 * resolved versions.
 */
export type PackageAdvisoryView = { ecosystem: string; name: string; advisories: string[] }
/**
 * A person's activity across a board's repos. Boundary form of `core_summary::PersonActivity`.
 * Descriptive, no ranking.
 */
export type PersonActivityView = { login: string; open_prs: PersonPrView[]; merged_prs: number; reviews_given: number; commits: number;
/**
 * `owner/name` of each board repo the person appears in.
 */
repos: string[] }
/**
 * One area a person has context in, for the pickup panel.
 */
export type PersonAreaView = { area: string; changes: number }
/**
 * A person's pickup profile: in-flight load, last-active time and the areas they have context
 * in. Descriptive, not a score or ranking.
 */
export type PersonPickupView = { login: string; open_prs: number; last_active: string | null; areas: PersonAreaView[] }
/**
 * One of a person's open PRs, for the per-person view. `repo` is `owner/name`.
 */
export type PersonPrView = { repo: string; number: number; title: string }
/**
 * One teammate's comparison stats for the People table. Boundary form of
 * `core_summary::PersonStats`.
 */
export type PersonStatsView = { login: string; commits: number; prs_opened: number; prs_merged: number; reviews_given: number; open_prs: number; approvals_given: number; self_merges: number;
/**
 * Median PR cycle time (open -> merge) in seconds, or null if nothing merged in the window.
 */
median_cycle_time_secs: number | null;
/**
 * Distinct UTC days with a work event (consistency/cadence).
 */
active_days: number;
/**
 * Median PR-open -> their-first-review latency in seconds, or null if nothing datable.
 */
median_review_latency_secs: number | null;
/**
 * Average change size (additions + deletions) over merged PRs with synced files, or null.
 */
avg_pr_churn: number | null;
/**
 * Issues closed by their merged PRs (authoritative links).
 */
issues_closed: number; ci_failures: number; off_hours_events: number; total_events: number }
/**
 * One board's row in the cross-board Portfolio: identity and daily trend series. No score or
 * tier; presented in board order, not ranked.
 */
export type PortfolioBoardView = { board_id: string; name: string; kind: string; trend: TrendPointView[] }
/**
 * A pull-request reference on a ritual agenda. Boundary form of `core_ritual::PrRef`.
 */
export type PrRefView = { id: string; number: number; title: string; url: string | null }
/**
 * A pull request in the list view: enough to pick one to inspect.
 */
export type PullRequestView = { id: string; number: number; title: string; state: string; author_login: string | null }
/**
 * What a reclaim did. No row count: it does not touch rows.
 */
export type ReclaimReportView = { used_before: number; used_after: number; freed_bytes: number }
/**
 * One watched repo's home-view state: its digest, attention items and upstream risk.
 */
export type RepoOverview = { repo_id: string; full_name: string; ownership: string; digest: DigestView; attention: AttentionView[];
/**
 * True count of this repo's attention items before the board-wide payload bound. Can exceed
 * `attention.len()` on a big board, since `board_overview` keeps only the most severe items.
 */
attention_total: number;
/**
 * Merged PRs that could not be judged for review coverage because they merged before the
 * earliest review synced for the repo. Reviews are fetched only for PRs changed since, so
 * such a PR was never checked. Not counted in `attention`.
 */
merged_without_review_unjudged: number;
/**
 * Merged PRs that could not be judged for a tracked work item because the repo has no
 * issue-link data synced. Same idea as above, for the `orphan_pr` signal.
 */
orphan_pr_unjudged: number; upstream: UpstreamAlertView[];
/**
 * Whether this repo's source is indexed for code search. `false` skips code fetch and embed.
 */
index_code: boolean;
/**
 * Whether this repo is a fork. The UI folds observed forks out of the flagged list.
 */
is_fork: boolean;
/**
 * This fork's upstream `owner/name`, so the UI can note "fork of X".
 */
parent_full_name: string | null }
/**
 * What one repo costs, estimated.
 */
export type RepoStorageView = { repo_id: string; full_name: string; commits: number; pull_requests: number; issues: number; code_files: number; index_chunks: number; rows: number;
/**
 * Summed byte length of the repo's stored text. Payload only, no indexes or page overhead.
 */
content_bytes: number;
/**
 * `index_chunks * embed_dim * 4`: exact for the raw vectors, a floor on the index cost.
 */
vector_bytes: number;
/**
 * `content_bytes + vector_bytes`. What to sort the list by.
 */
estimated_bytes: number }
/**
 * One scorecard rule's outcome. `status` is "pass" | "fail" | "unknown"; `unknown` means the
 * underlying fact was never observed, which is not a `fail`.
 */
export type RuleResultView = { rule: string; tier: string; status: string; detail: string }
/**
 * A sprint's say-do: committed vs delivered plus scope churn. `ratio` is null when nothing was
 * committed.
 */
export type SayDoView = { sprint_id: string; sprint_name: string; state: string | null; committed_on: string | null; committed: number; delivered: number; carryover: number; added: number; removed: number; ratio: number | null }
/**
 * A repo's scorecard for the UI.
 */
export type ScorecardView = { repo_id: string; full_name: string; tier: string; rules: RuleResultView[] }
/**
 * One semantic-search hit: the matched chunk and its similarity score.
 */
export type SearchHit = { ref_kind: string; ref_id: string; chunk: string; score: number;
/**
 * Forge web URL of the source file for a code hit. `None` for activity hits or an unknown
 * forge web base.
 */
url: string | null }
/**
 * Application settings for the UI. Boundary form of `core_store::Settings`.
 */
export type SettingsView = { sync_period_secs: number; stale_pr_days: number;
/**
 * Slack-compatible incoming-webhook URL for the digest push, or null if unset.
 */
digest_webhook_url: string | null;
/**
 * The scheduled-digest cadence in hours, or null if off.
 */
digest_schedule_hours: number | null;
/**
 * Whether local-LLM narration is enabled at runtime.
 */
llm_enabled: boolean;
/**
 * The selected GGUF model filename, or null to use the env default.
 */
llm_model: string | null;
/**
 * Disk the database may use, in megabytes, or null for no limit.
 */
storage_budget_mb: number | null }
/**
 * One attention-signal preference for a board: signal id, label, and whether the board flags it.
 */
export type SignalPrefView = { signal: string; label: string; enabled: boolean }
/**
 * One storage group's share of the database.
 */
export type StorageGroupView = {
/**
 * "search_index" | "chunk_text" | "activity" | "code" | "history" | "config" | "internal".
 */
group: string; bytes: number; estimated: boolean }
/**
 * Storage accounting for the Debug view: boundary form of `core_store::StorageReport` plus the
 * on-disk assets the core cannot see. Byte figures are paired with measured/estimated.
 */
export type StorageReportView = {
/**
 * "dbstat" (measured page counts) or "payload_estimate" (summed value lengths).
 */
method: string;
/**
 * True when the table breakdown came from real page counts.
 */
measured: boolean; db_path: string;
/**
 * The database file's size on disk plus its WAL and shared-memory files. Null if in memory.
 */
file_bytes: number | null; wal_bytes: number | null; shm_bytes: number | null; page_size: number; page_count: number;
/**
 * `page_count * page_size`: what SQLite claims inside the file. Measured either way.
 */
reserved_bytes: number;
/**
 * Claimed pages holding nothing. Only a VACUUM returns them to the file system, so the file
 * does not shrink after a delete.
 */
free_bytes: number; attributed_bytes: number;
/**
 * `reserved - attributed - free`. Near zero when measured; most of the file under the
 * estimate, which cannot see indexes or page overhead.
 */
residual_bytes: number; groups: StorageGroupView[]; tables: StorageTableView[];
/**
 * Per repo. Always an estimate: SQLite attributes pages to tables, never to rows.
 */
repos: RepoStorageView[];
/**
 * Model files and directories outside the database.
 */
assets: AssetStorageView[]; embed_dim: number }
/**
 * The live storage state: database cost, the user's ceiling, and whether the app is running,
 * warning or stopped. Cheap enough to poll (three pragmas, two `stat` calls, a walk of the model
 * dirs), unlike [`storage_report`], whose `dbstat` pass walks every page.
 */
export type StorageStateView = {
/**
 * "normal" | "warning" | "full".
 */
pressure: string;
/**
 * True when syncing and indexing are stopped.
 */
stopped: boolean;
/**
 * The plain-language sentence, built in the core so the banner and Settings card agree.
 */
message: string;
/**
 * The database file plus its write-ahead log: the figure the budget is enforced against.
 */
used_bytes: number;
/**
 * The configured ceiling in bytes, or null when the user chose no limit.
 */
budget_bytes: number | null;
/**
 * The same ceiling in megabytes, the unit the settings field edits.
 */
budget_mb: number | null;
/**
 * Claimed pages holding nothing. A delete moves pages here; the file shrinks only on reclaim.
 */
free_bytes: number;
/**
 * The model files on disk. Reported beside the budget, not inside it: models are fixed-size
 * artifacts the user chose knowing their size.
 */
model_bytes: number }
/**
 * One table's share, with its indexes and (for vector / full-text tables) shadow tables.
 */
export type StorageTableView = { name: string; group: string; bytes: number; estimated: boolean }
/**
 * One repo in the store, for the Debug forget list. `pinned` is the user's choice, `discovered`
 * means it came from a board's people; a repo with neither is watched by nothing.
 */
export type StoredRepoView = { repo_id: string; full_name: string; pinned: boolean; discovered: boolean }
/**
 * Typed event the scheduler emits after polling one source: the source id and either the
 * per-type counts (`summary`, on success) or the `error` string.
 * A granular sync progress update. Boundary form of `core_sync::SyncProgress`. `phase` is
 * "planning" or "syncing"; `item` is a board (planning) or repo full-name (syncing) with its
 * position; `step` is the sub-step within a repo. When `finished`, the completion fields
 * (`source_id`, `ok`, `summary`, `error`) describe the repo's result.
 */
export type SyncProgressEvent = { phase: string; item: string; item_done: number; item_total: number; step: string | null; step_done: number; step_total: number; finished: boolean; source_id: string | null; ok: boolean; summary: SyncSummary | null; error: string | null }
/**
 * What a `sync_repo` run persisted: one count per activity type.
 */
export type SyncSummary = { commits: number; pull_requests: number; issues: number; releases: number; reviews: number; ci_runs: number; dependencies: number; code_files: number }
/**
 * A registered tracker (Jira site). `connected` reflects only a stored token: a public site needs
 * none, and the two cannot be told apart.
 */
export type TrackerView = { id: string; name: string; kind: string; base_url: string; email: string | null; connected: boolean }
/**
 * A board's "what changed" summary for the UI.
 */
export type TrendDeltasView = { days: number; deltas: MetricDeltaView[] }
/**
 * One day on a board's metric trend. Boundary form of `core_summary::TrendPoint`.
 */
export type TrendPointView = { captured_on: string; wip: number; stale_open_prs: number; merged_without_review: number; attention_count: number }
/**
 * An upstream-risk alert for the UI: a depended-on repo and how many attention items it has.
 */
export type UpstreamAlertView = { repo_id: string; attention_count: number }
/**
 * One point of a board's say-do velocity trend: a sprint with a frozen commitment and a
 * measurable ratio. Carries the counts the ratio is made of, so 1-of-1 is not read as 20-of-20.
 */
export type VelocityPointView = { sprint_id: string; sprint_name: string; committed_on: string; committed: number; delivered: number; ratio: number }
/**
 * When a person works: a 7x24 (weekday x hour, UTC) activity heatmap over a window,
 * `buckets[weekday*24 + hour]`, weekday 0 = Sunday. Read-only; works with no token.
 */
export type WorkPatternView = { buckets: number[] }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
